name: urbansight
description: UrbanSight - Urban issue reporting app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.3.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.6
  image_picker: ^1.2.1
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  provider: ^6.1.5
  intl: ^0.20.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
